os: osx
osx_image: xcode11.2
script: 
   - xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
   - xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform:iOS Simulator, id:B9E1891B-A775-4DB6-9567-8FDD1283C63B, OS:13.2.2, name:iPhone 11" ONLY_ACTIVE_ARCH=YESbranches
only:
  - master
  - development
